from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'dc8e89e781a0'
down_revision: str | Sequence[str] | None = 'c1e5b2a9f4d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reward_cap_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_key', sa.Date(), nullable=False),
    sa.Column('xp_legend_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coin_legend_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timezone_policy', sa.String(length=20), server_default='UTC+8', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_reward_cap_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_reward_cap_usage')),
    sa.UniqueConstraint('user_id', 'date_key', name=op.f('uq_daily_reward_cap_usage_user_id'))
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.Enum('monthly', 'annual', name='subscriptionplantype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'past_due', name='subscriptionstatus', native_enum=False, create_constraint=True), server_default='active', nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index('ix_subscriptions_user_status_period', 'subscriptions', ['user_id', 'status', 'current_period_end'], unique=False)
    op.create_table('learning_path_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'failed', name='learningpathstatus', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('trigger_type', sa.Enum('auto_lazy', 'regenerate', 'manual_retry', name='pathtriggertype', native_enum=False, create_constraint=True), server_default='auto_lazy', nullable=False),
    sa.Column('generator_config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_content_hash', sa.String(length=64), nullable=True),
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_cleanup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_learning_path_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_job_id'], ['jobs.id'], name=op.f('fk_learning_path_versions_generation_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_path_versions')),
    sa.UniqueConstraint('document_id', 'mode', 'version_no', name=op.f('uq_learning_path_versions_document_id'))
    )
    op.create_index('ix_learning_path_versions_document_mode_created', 'learning_path_versions', ['document_id', 'mode', 'created_at'], unique=False)
    op.create_index('ix_learning_path_versions_failed_cleanup_at', 'learning_path_versions', ['failed_cleanup_at'], unique=False)
    op.create_index('ix_learning_path_versions_status', 'learning_path_versions', ['status'], unique=False)
    op.create_table('learning_path_nodes',
    sa.Column('path_version_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.Enum('skill_tree', 'unit', 'level', name='learningpathnodetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('node_key', sa.String(length=120), nullable=False),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('is_mode_branch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unlock_rule_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('question_selector_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_node_id'], ['learning_path_nodes.id'], name=op.f('fk_learning_path_nodes_parent_node_id_learning_path_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_version_id'], ['learning_path_versions.id'], name=op.f('fk_learning_path_nodes_path_version_id_learning_path_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_path_nodes')),
    sa.UniqueConstraint('path_version_id', 'node_key', name=op.f('uq_learning_path_nodes_path_version_id'))
    )
    op.create_index('ix_learning_path_nodes_parent_sort', 'learning_path_nodes', ['parent_node_id', 'sort_order'], unique=False)
    op.create_table('path_regeneration_records',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('path_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_path_regeneration_records_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_version_id'], ['learning_path_versions.id'], name=op.f('fk_path_regeneration_records_path_version_id_learning_path_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_path_regeneration_records_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_path_regeneration_records'))
    )
    op.create_index('ix_path_regeneration_records_doc_mode_created', 'path_regeneration_records', ['document_id', 'mode', 'created_at'], unique=False)
    op.create_table('legend_review_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_version_id', sa.UUID(), nullable=False),
    sa.Column('unit_node_id', sa.UUID(), nullable=False),
    sa.Column('legend_round_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_legend_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['path_version_id'], ['learning_path_versions.id'], name=op.f('fk_legend_review_progress_path_version_id_learning_path_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_node_id'], ['learning_path_nodes.id'], name=op.f('fk_legend_review_progress_unit_node_id_learning_path_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_legend_review_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legend_review_progress')),
    sa.UniqueConstraint('user_id', 'path_version_id', 'unit_node_id', name=op.f('uq_legend_review_progress_user_id'))
    )
    op.create_index('ix_legend_review_progress_user_path', 'legend_review_progress', ['user_id', 'path_version_id'], unique=False)
    op.create_table('learning_path_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_version_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'unlocked', 'completed', name='learningpathprogressstatus', native_enum=False, create_constraint=True), server_default='locked', nullable=False),
    sa.Column('first_completed_run_id', sa.UUID(), nullable=True),
    sa.Column('completed_runs_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['first_completed_run_id'], ['runs.id'], name=op.f('fk_learning_path_progress_first_completed_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['learning_path_nodes.id'], name=op.f('fk_learning_path_progress_node_id_learning_path_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_version_id'], ['learning_path_versions.id'], name=op.f('fk_learning_path_progress_path_version_id_learning_path_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_path_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_path_progress')),
    sa.UniqueConstraint('user_id', 'path_version_id', 'node_id', name=op.f('uq_learning_path_progress_user_id'))
    )
    op.create_index('ix_learning_path_progress_user_path', 'learning_path_progress', ['user_id', 'path_version_id'], unique=False)
    op.add_column('inventories', sa.Column('quota_max', sa.Integer(), nullable=True))
    op.add_column('inventories', sa.Column('refill_days', sa.Integer(), nullable=True))
    op.add_column('inventories', sa.Column('last_refill_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventories', sa.Column('next_refill_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('source_path_version_id', sa.UUID(), nullable=True))
    op.add_column('runs', sa.Column('source_level_node_id', sa.UUID(), nullable=True))
    op.add_column('runs', sa.Column('is_legend_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('runs', sa.Column('legend_reward_rate', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False))
    op.add_column('runs', sa.Column('version_reward_discount', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False))
    op.create_foreign_key(op.f('fk_runs_source_path_version_id_learning_path_versions'), 'runs', 'learning_path_versions', ['source_path_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_runs_source_level_node_id_learning_path_nodes'), 'runs', 'learning_path_nodes', ['source_level_node_id'], ['id'], ondelete='SET NULL')
    op.add_column('shop_offers', sa.Column('quota_type', sa.Enum('unlimited', 'personal_cap', 'auto_refill', name='quotatype', native_enum=False, create_constraint=True), server_default='unlimited', nullable=False))
    op.add_column('shop_offers', sa.Column('max_capacity', sa.Integer(), nullable=True))
    op.add_column('shop_offers', sa.Column('refill_days', sa.Integer(), nullable=True))
    op.add_column('shop_offers', sa.Column('tier_required', sa.Enum('free', 'super', name='tierrequired', native_enum=False, create_constraint=True), server_default='free', nullable=False))
    op.add_column('shop_offers', sa.Column('experiment_flag', sa.String(length=80), nullable=True))
    op.add_column('shop_offers', sa.Column('item_type', sa.Enum('coin_pack', 'streak_freeze', 'time_treasure', 'revival', name='itemtype', native_enum=False, create_constraint=True), server_default='coin_pack', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_offers', 'item_type')
    op.drop_column('shop_offers', 'experiment_flag')
    op.drop_column('shop_offers', 'tier_required')
    op.drop_column('shop_offers', 'refill_days')
    op.drop_column('shop_offers', 'max_capacity')
    op.drop_column('shop_offers', 'quota_type')
    op.drop_constraint(op.f('fk_runs_source_level_node_id_learning_path_nodes'), 'runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_runs_source_path_version_id_learning_path_versions'), 'runs', type_='foreignkey')
    op.drop_column('runs', 'version_reward_discount')
    op.drop_column('runs', 'legend_reward_rate')
    op.drop_column('runs', 'is_legend_review')
    op.drop_column('runs', 'source_level_node_id')
    op.drop_column('runs', 'source_path_version_id')
    op.drop_column('inventories', 'next_refill_at')
    op.drop_column('inventories', 'last_refill_at')
    op.drop_column('inventories', 'refill_days')
    op.drop_column('inventories', 'quota_max')
    op.drop_index('ix_learning_path_progress_user_path', table_name='learning_path_progress')
    op.drop_table('learning_path_progress')
    op.drop_index('ix_legend_review_progress_user_path', table_name='legend_review_progress')
    op.drop_table('legend_review_progress')
    op.drop_index('ix_path_regeneration_records_doc_mode_created', table_name='path_regeneration_records')
    op.drop_table('path_regeneration_records')
    op.drop_index('ix_learning_path_nodes_parent_sort', table_name='learning_path_nodes')
    op.drop_table('learning_path_nodes')
    op.drop_index('ix_learning_path_versions_status', table_name='learning_path_versions')
    op.drop_index('ix_learning_path_versions_failed_cleanup_at', table_name='learning_path_versions')
    op.drop_index('ix_learning_path_versions_document_mode_created', table_name='learning_path_versions')
    op.drop_table('learning_path_versions')
    op.drop_index('ix_subscriptions_user_status_period', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('daily_reward_cap_usage')
    # ### end Alembic commands ###
